### ISSUE TITLE
dataset con nome colonna duplicato

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#11]
### Comportamento atteso e comportamento effettivo
Non è un problema funzionale, ma lo segnalo perché potrebbe essere la causa di #10:   il dataset [STRADARIO DEL COMUNE DI PALERMO, MARZO_2017](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=524), se scaricato in CSV due colonne con lo stesso nome `Barrato`.

### Passi per riprodurre il problema
Scaricare in formato CSV

### Browser e sistema operativo usato
Chrome 66, Win 10

**Comment by ComunePalermo** [comment]
Su questa segnalazione non possiamo intervenire in quanto si tratta di un formato file sporco in origine.
Invieremo una segnalazione al responsabile Open Data Ciro Spataro, affinché si attivi per fare sostituire il file con un formato corretto.
