### ISSUE TITLE
L'encoding di risposta, non corrisponde con l'encoding dichiarato

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#12]
### Comportamento atteso e comportamento effettivo
Se si fa una chiamata ad esempio al dataset https://opendata.comune.palermo.it/opendata-dataset.php?dataset=948, il server risponde con heading `ISO-8859-15`, mentre nella pagina è dichiarato come `utf-8`.

Questo potrebbe dare problemi di lettura _machine to machine_, perché alcuni client forzano il reading rispetto alla risposta del server.

### Passi per riprodurre il problema
Una chiamata con wget

    wget -S "https://opendata.comune.palermo.it/opendata-dataset.php?dataset=948"

Restituisce

```
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Date: Thu, 05 Apr 2018 17:37:59 GMT
  Server: Microsoft-IIS/6.0 mod_fcgid/2.3.9
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
  Cache-Control: no-store, no-cache, must-revalidate
  Pragma: no-cache
  Set-Cookie: PHPSESSID=7lfh2hvnvhfmr5vs050cdlo615; path=/; secure; HttpOnly
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer-when-downgrade
  Access-Control-Allow-Origin: *
  Connection: close
  Transfer-Encoding: chunked
  Content-Type: text/html; charset=ISO-8859-15
```
Una con httpie

    http -h "https://opendata.comune.palermo.it/opendata-dataset.php?dataset=948"

restituisce

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, must-revalidate
Connection: close
Content-Type: text/html; charset=ISO-8859-15
Date: Thu, 05 Apr 2018 17:42:51 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Referrer-Policy: no-referrer-when-downgrade
Server: Microsoft-IIS/6.0 mod_fcgid/2.3.9
Set-Cookie: PHPSESSID=ogniqdtk252cb61j8fhc5b6n06; path=/; secure; HttpOnly
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
```

In entrambe `charset=ISO-8859-15`

### Browser e sistema operativo usato
Non browser, ma wget e httpie via shell.

**Comment by aborruso** [comment]
Aggiungo che il problema della difformità di encoding è presente su tutto il sito del comune.

Andrebbe cambiata globalmente la risposta del server (è IIS??) su tutto il sito. Ma qui mi fermo, che non è cosa mia.

**Comment by ComunePalermo** [comment]
L'impatto sulla modifica riguarda l'intero sistema web del comune.
Se prima non ultimiamo la migrazione del db oracle su utf8 non possiamo modificare, e la migrazione comporta dovere riscrivere parecchio codice sia nelle pagine web che nei pannelli di amministrazione dei contenuti.
Dobbiamo convivere con il problema ancora per qualche mese.
