### ISSUE TITLE
Il link a github è poco visibile

### ISSUE THREAD

**Issue by nelsonmau** [ComuneDiPalermo/PortaleOpendata#13]
Sulla [pagina del comune](https://www.comune.palermo.it/noticext.php?id=17766) dove si annuncia questo spazio online, il link è poco visibile.

![compa1](https://user-images.githubusercontent.com/1769578/38509959-c0e4bd94-3c23-11e8-8b1e-4bc5d9a115cc.png)

si potrebbe invece mettere con underline perché sia più facile vederlo

![compa2](https://user-images.githubusercontent.com/1769578/38510007-e8c7b9a6-3c23-11e8-8a0e-6d7378600a33.png)

grazie

**Comment by aborruso** [comment]
Sì è vero, io proprio non lo vedevo. Ho trovato infatti utile crearmi un foglio di stile personalizzato che viene forzatamente applicato al sito https://medium.com/mai-piu-senza/lo-stile-è-tutto-53d2e73dbb96#774b

È off-topic rispetto al portale, ma anche a me sembra importante.

**Comment by marcofromsicily** [comment]
Si potrebbe aggiungere il logo GitHub accanto a quelli Facebook e Twitter nella home del portale open data.

Riferimento ai loghi della issue #4

**Comment by aborruso** [comment]
@nelsonmau è stato cambiato il foglio di stile puoi chiudere :)

**Comment by nelsonmau** [comment]
grazie!
