### ISSUE TITLE
Sinistri Stradali 2015 e 2016 Dataset non presenti

### ISSUE THREAD

**Issue by gbvitrano** [ComuneDiPalermo/PortaleOpendata#14]
### Comportamento atteso e comportamento effettivo
[Dataset 2015](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375)-  **Dataset non presente**  - [qui il link al vecchio portale](https://www.comune.palermo.it/opendata_dld.php?id=375)

[Dataset 2016](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=523) - **Dataset klm non presente**, nel [vecchio portale](https://www.comune.palermo.it/opendata_dld.php?id=523) è scaricabile oltre al fotmato klm  anche i file in formato zip e csv

### Passi per riprodurre il problema
[Riferimento opendata non presente dataset 2015](https://opendata.comune.palermo.it/ws.php?id=451&fmt=csv)
 [link non valido dataset 2016](https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_20032017144957.kml)

### Browser e sistema operativo usato
Chrome - Win 10

**Comment by ComunePalermo** [comment]
Aggiornato i due dataset.
