### ISSUE TITLE
Richiesta: avere i permalink per categorie e tag

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#15]
### Comportamento atteso e comportamento effettivo
Al momento non è possibile inviare ad esempio un'email che contiene  il link alla pagina con i soli dataset della categoria `Dati sul territorio`.

Sarebbe comodo avere la possibilità di richiedere il tutto anche in GET e attivare quindi URL come

    https://opendata.comune.palermo.it/opendata-archivio-dataset.php?term=4&src=2

E sarebbe comodo attivare la stessa cosa per i tag.

### Passi per riprodurre il problema
Aprire l'[achivio](https://opendata.comune.palermo.it/opendata-archivio-dataset.php) e fare click su una categoria. Non viene prodotto un URL univoco per quella categoria.

### Browser e sistema operativo usato
Firefox 59, Win 10

**Comment by ComunePalermo** [comment]
Spiace ma la funzione utilizzata nella pagina non prevede allo stato attuale tale implementazione.

Terremo conto della richiesta nelle prossime release.
