### ISSUE TITLE
Dataset con risorse irraggiungibili e con URI DCAT errato

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#16]
### Comportamento atteso e comportamento effettivo
[Questo](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=441) dataset  non consente il download in alcun formato.

Inoltre nella descrizione DCAT c'è un errore. C'è un `\` nell'URL

Si ha 

    https://opendata.comune.palermo.it/js/server/uploads/dataset/xml/\VIS_DATASET_AMBIENTE_04_1999.xml

E non 

    https://opendata.comune.palermo.it/js/server/uploads/dataset/xml/VIS_DATASET_AMBIENTE_04_1999.xml

### Passi per riprodurre il problema
- Aprire [il dataset](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=441) e provare a scaricare la risorsa in uno dei formati;
- aprire l'endpoint DCAT e cercare la stringa `\VIS_DATASET_AMBIENTE_04_1999.xml`

### Browser e sistema operativo usato
Firefox 59, Win 10

**Comment by ComunePalermo** [comment]
BUG RISOLTO, si trattava di un errore in fase di caricamento del dataset
