### ISSUE TITLE
Circa 100 risorse danno errore 404

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#18]
### Comportamento atteso e comportamento effettivo
A partire dai dati del catalogo DCAT-AP_IT, ho provato a verificare se tutte le risorse fossero raggiungibili e circa 100 su 1000 non lo sono. Le riporto sotto.

Alcuni 404 potrebbero essere correlati a #17 .

### Passi per riprodurre il problema
Provare il download con un qualsiasi client. Un primo test è fare click sull'URL della colonna **Risorsa** di sotto.

### Browser e sistema operativo usato
Ho usato cURL a riga di comando.

---

|Dataset|Risorsa|
|---|---|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1015|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/nopath|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=121|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013130800.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=131|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013145254.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=134|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013145932.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=153|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013160915.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=161|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013162328.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=219|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013115311.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=223|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013121210.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=228|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013122001.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=259|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013153448.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=265|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013103000.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=268|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013101005.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=269|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013101356.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=27|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_20022013155821.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=273|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013102513.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=277|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013161404.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=278|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013102347.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=281|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/nopath|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=281|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013102225.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=283|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_03052013103446.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=286|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22022013162949.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=320|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_16022015095803.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=321|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_16022015100804.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=328|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_08042015182900.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=333|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_07072015102950.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=334|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_07072015123402.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=336|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_07072015123604.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=338|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_30072015131336.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=339|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_30072015131412.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=340|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_30072015131425.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=341|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_30072015131435.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=343|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_04092015102300.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=344|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_04092015102301.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=345|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_04092015103422.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=350|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_02122015094031.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=351|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_29122015115746.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=360|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_17042016173001.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=364|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_22042016123001.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=365|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_25042016172537.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=367|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_10052016133125.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=369|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_13052016122520.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=373|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_15062016110006.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=374|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_15062016171151.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_29062016140430.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_28062016105809.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_28062016105859.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_28062016105654.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_28062016105353.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=375|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_28062016105737.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=376|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_29062016141656.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=377|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_29062016142214.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=378|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_30062016141712.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=380|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30062016142710.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=380|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_30062016142619.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=381|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_08072016104909.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=382|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_08072016115204.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=385|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_29072016103317.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=390|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_26092016113631.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=395|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_24112016124431.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=40|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_20022013164719.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=415|https://opendata.comune.palermo.it/js/server/uploads/dataset/xml/VIS_DATASET_AMBIENTE_02_1997.xml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=42|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_20022013165324.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=427|https://opendata.comune.palermo.it/js/server/uploads/dataset/xml/VIS_DATASET_AMBIENTE_02_1998.xml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=451|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_06022017123845.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=453|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017122529.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=455|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017115642.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=458|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30012017083616.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=459|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30012017084050.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=461|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30012017110458.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=462|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30012017110946.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=463|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30012017120852.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=464|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017110116.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=465|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017104250.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=466|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_30012017130713.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=467|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017103508.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=468|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017102533.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=469|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017101517.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=471|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_03022017090814.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=505|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_13022017131405.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=505|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_15062017185328.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=505|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_13022017131257.shp|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=505|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_13022017131334.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=506|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_06022017125419.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=523|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_20032017144826.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=523|https://opendata.comune.palermo.it/js/server/uploads/dataset/kml/_20032017144957.kml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=523|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_20032017144516.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=70|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013100736.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=71|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013101323.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=799|http://circoscrizioni2017.comune.palermo.it/TOT_1_9990021.xml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=848|https://opendata.comune.palermo.it/js/server/uploads/dataset/shp/_15062017122629.zip|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=849|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_13122017143834.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=9|https://opendata.comune.palermo.it/js/server/uploads/attivita/pdf/nopath|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=92|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013113800.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=954|https://opendata.comune.palermo.it/js/server/uploads/dataset/xml/VIS_DATASET_AMBIENTE_10_2008.xml|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=96|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013123530.csv|
|https://opendata.comune.palermo.it/opendata-dataset.php?dataset=98|https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013115147.csv|
||

**Comment by ComunePalermo** [comment]
Le risorse sono state verificate

**Comment by aborruso** [comment]
@ComunePalermo ho fatto "a mano" un test su due dei dataset di sopra:

- https://opendata.comune.palermo.it/opendata-dataset.php?dataset=121
- https://opendata.comune.palermo.it/opendata-dataset.php?dataset=131

A fondo messaggio due porzioni dell'[endpoint DCAT](https://opendata.comune.palermo.it/dcat/dcat.php) correlati a questi due dataset.

Nel **121** si fa riferimento al CSV:
https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013130800.csv

Nel **131** si fa riferimento al CSV:
https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013145254.csv

Entrambi questi CSV danno errore 404. È normale?

Grazie


### 121

```
<https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013130800.csv>
  a dcatapit:Distribution, dcat:Distribution ;
  dcat:downloadURL <https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013130800.csv> ;
  dcat:accessURL <https://opendata.comune.palermo.it/opendata-dataset.php?dataset=121> ;
  dc:format <http://publications.europa.eu/resource/authority/file-type/CSV> ;
  dc:license <http://creativecommons.org/licenses/by/4.0/> ;
  dc:title "Distribuzione CSV del dataset ARRIVI E PRESENZE DEI TURISTI NEGLI ESERCIZI ALBERGHIERI E IN ALTRE STRUTTURE RICETTIVE - ANNO 2011" ;
  dc:description "Distribuzione CSV del dataset ARRIVI E PRESENZE DEI TURISTI NEGLI ESERCIZI ALBERGHIERI E IN ALTRE STRUTTURE RICETTIVE - ANNO 2011" .
```

### 131

```
<https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013145254.csv>
  a dcatapit:Distribution, dcat:Distribution ;
  dcat:downloadURL <https://opendata.comune.palermo.it/js/server/uploads/dataset/csv/_21022013145254.csv> ;
  dcat:accessURL <https://opendata.comune.palermo.it/opendata-dataset.php?dataset=131> ;
  dc:format <http://publications.europa.eu/resource/authority/file-type/CSV> ;
  dc:license <http://creativecommons.org/licenses/by/4.0/> ;
  dc:title "Distribuzione CSV del dataset ARRIVI E PRESENZE TURISTI STRANIERI IN ESERCIZI ALBERGHIERI E IN ALTRE STRUTTURE RICETTIVE 2011" ;
  dc:description "Distribuzione CSV del dataset ARRIVI E PRESENZE TURISTI STRANIERI IN ESERCIZI ALBERGHIERI E IN ALTRE STRUTTURE RICETTIVE 2011" .
```

**Comment by aborruso** [comment]
Questa è stata chiusa, ma ci sono ancora risorse nell'elenco di sopra che danno errore 404.

Ho aperto nuova issue #24
