### ISSUE TITLE
Please provide a static URL for the GTFS dataset

### ISSUE THREAD

**Issue by patperu** [ComuneDiPalermo/PortaleOpendata#20]
Hello,
to use the AMAT GTFS data via the [Navitia.io](https://www.navitia.io/) API it's necessary to provide a static URL. 

Currently the traffic data from Palermo is outdated (id 15) https://navitia.opendatasoft.com/explore/dataset/it/table/?sort=type_file

We had the same issue two years ago in the OpenAMAT repo https://github.com/openamat/Official-Data/issues/16

It would be very kind, if you could provide a new static link. As soon as we have a link I would inform Navitia.

Thank you
Patrick

**Comment by aborruso** [comment]
@ComunePalermo  ci sono novità su questa cosa??

Diversi servizi, anche internazionali, che accedano a dati ufficiali, non sono più aggiornati perché non c'è più l'URL univoco.

È uno dei dataset più importanti e con impatto per tutti.

Grazie

**Comment by ComunePalermo** [comment]
Buongiorno, abbiamo provveduto ad implementare la funzione che permette di rendere sempre disponibile l'ultima versione del dataset.
Il permalink dell'ultima versione è il seguente:
([https://opendata.comune.palermo.it/js/server/uploads/dataset/gtfs/amat_gtfs.zip])
La pagina del dataset ripropone sempre il superiore link.

**Comment by patperu** [comment]
Thank you! I notified Navitia [https://groups.google.com/d/msg/navitia/3nMEg57C_sU/D6QuajTDCAAJ](https://groups.google.com/d/msg/navitia/3nMEg57C_sU/D6QuajTDCAAJ)

**Comment by aborruso** [comment]
Grazie @patperu e @ComunePalermo
