### ISSUE TITLE
Output dataset errato

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#21]
### Comportamento atteso e comportamento effettivo

Il dataset [1024](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1024) ha tutti gli output errati, basta guardare le anteprime in CSV, JSON e XML.

Nel CSV ad esempio ci sono le `"` a inizio e fine riga. Dovrebbero non esserci completamente o essere a inizio e fine di ogni campo.

```
"ANNO DI RIFERIMENTO ;NUMERO VISITATORI COLLEZIONE PERMANENTE;NUMERO VISITATORI MOSTRE TEMPORANEE ;MOSTRE TEMPORANEE REALIZZATE;GIORNI ANNUALI DI APERTURA AL PUBBLICO;NUMERO DI ATTIVITA' DIDATTICA LABORATORI;NUMERO VISITE SCUOLE;NUMERO ALUNNI;NUMERO VISITE GUIDATE;RESTAURI EFFETTUATI OPERE D'ARTE"
"2011;20616;3208;4;314;253;280;7019;114;2"
"2012;16517;4253;3;313;70;211;5275;71;6"
"2013;18009;1655;5;313;124;249;6230;76;2"
"2014;18541;3586;5;316;10;195;4912;126;5"
"2015;24135;3231;4;314;58;225;6082;114;12"
"2016;27652;19021;6;318;77;65;12388;144;6"
"2017;28428;33186;3;316;345;695;17359;235;3"
```

### Passi per riprodurre il problema

Aprire le anteprime e visualizzare l'output.

### Browser e sistema operativo usato

Firefox 59 e Windows 10

**Comment by cirospat** [comment]
ho dato un occhiata alla preview CSV e il separatore è la virgola "," e i doppi apici `"` a inizio e fine di ogni campo non ci sono. Credo il Webmaster abbia provveduto a verificare quello che hai segnalato tu e abbia corretto

![image](https://user-images.githubusercontent.com/3757525/42676124-3485728c-8677-11e8-85bd-815129b8d1d8.png)

**Browser e sistema operativo usato**
Chrome vers. 67 e Windows 7

**Comment by aborruso** [comment]
Buongiorno @cirospat , confermo che il problema con `"` e separatore sembra risolto.

Internamente però ci sono ancora dei problemi che mi sembrano correlati.
Se si apre la preview o l'output in json, per un item si ha:

```json
[
  {
    "ANNO DI RIFERIMENTO,NUMERO_VISITATORI_COLLEZIONE_PERMANENTE,NUMERO_VISITATORI_MOSTRE_TEMPORANEE,MOSTRE_TEMPORANEE_REALIZZATE,GIORNI_ANNUALI_DI APERTURA_AL_PUBBLICO,NUMERO_DI ATTIVITA_DIDATTICA_LABORATORI,NUMERO_VISITE_SCUOLE,NUMERO_ALUNNI,NUMERO_VISITE_GUIDATE,RESTAURI_EFFETTUATI_OPERE_ARTE": "2011,20616,3208,4,314,253,280,7019,114,2"
  }
]
```

Un unico campo che ha per etichetta ""ANNO DI RIFERIMENTO,NUMERO_VISITATORI_COLLEZIONE_PERMANENTE,NUMERO_VISITATORI_MOSTRE_TEMPORANEE,MOSTRE_TEMPORANEE_REALIZZATE,GIORNI_ANNUALI_DI APERTURA_AL_PUBBLICO,NUMERO_DI ATTIVITA_DIDATTICA_LABORATORI,NUMERO_VISITE_SCUOLE,NUMERO_ALUNNI,NUMERO_VISITE_GUIDATE,RESTAURI_EFFETTUATI_OPERE_ARTE"" e come unico valore la stringa "2011,20616,3208,4,314,253,280,7019,114,2".

Mentre dovrebbero essere 10 campi

```json
[
  {
    "ANNO DI RIFERIMENTO": 2011,
    "NUMERO_VISITATORI_COLLEZIONE_PERMANENTE": 20616,
    "NUMERO_VISITATORI_MOSTRE_TEMPORANEE": 3208,
    "MOSTRE_TEMPORANEE_REALIZZATE": 4,
    "GIORNI_ANNUALI_DI APERTURA_AL_PUBBLICO": 314,
    "NUMERO_DI ATTIVITA_DIDATTICA_LABORATORI": 253,
    "NUMERO_VISITE_SCUOLE": 280,
    "NUMERO_ALUNNI": 7019,
    "NUMERO_VISITE_GUIDATE": 114,
    "RESTAURI_EFFETTUATI_OPERE_ARTE": 2
  }
]
```

Anche l'XML di output credo sia non valido

**Comment by cirospat** [comment]
Andrea, devo fare una domanda per capire un po di più la questione:
il CSV è valido ?

**ECCO IL PROCESSO DI GENERAZIONE DEL FILE CSV CARICATO SUL PORTALE OPEN DATA**
Ho provveduto - insieme alla collega dell'Ufficio della GAM - a elaborare il file in formato CSV e a caricarlo nel pannello di controllo del portale open data (nuova versione del portale che prevede il visualizzatore dei dati nei formati CSV, XML e JSON).
Il file CSV deriva da un Google spreadsheet dove le colleghe della GAM raccolgono i dati.
Poi si procede al download del file in formato CSV direttamente dalla console di Google spreadsheet.
Lo apriamo una volta scaricato in CSV e controlliamo come vengono esposti i dati. Una volta che verifichiamo visivamente la corretta esposizione dei dati provvediamo all'upload sul pannello di controllo del portale open data.

Per gli altri formati (XML e JSON), che vengono generati dal software interno del portale open data (software che non conosco), non so risponderti in merito a eventuali  errori di visualizzazione/esposizione dei dati.
Credo che il Webmaster (il suo staff) può rispondere in merito a quest'ultimo punto. Sarei anche io interessato a capirne di più in merito perchè questo problema ho notato che si sta presentando frequentemente quando si caricano formati CSV.
Purtroppo fino a quando non ci saranno applicativi gestionali che esportano automaticamente dati in formato CSV/XML/JSON online, e quindi fino a quando andremo avanti con i caricamenti manuali di formati CSV, questo problema si ripresenterà.

**Comment by aborruso** [comment]
@cirospat il nuovo CSV caricato, quello separato da `,`, era corretto.

Però il sistema di preview non lo leggeva correttamente e dava errori. Adesso che ne è stato caricato uno, separato da `;`, la preview è ok.

Io vi consiglio di gestire anche l'upload di CSV separati da `,` e al limite sceglierlo come default. E come encoding l'UTF-8.

Perché è il formato di default di input e di outuput della maggior parte dei sistemi. In comune credo che voi utilizzate google drive, e ad esempio non c'è modo da google drive di cambiare il separatore in output, ed è sempre `,`.
Questo vi costringerebbe con i CSV che caricate a fare prima il download da drive, fare poi le modifiche del separatore, e poi fare l'upload sul portale.

Saluti e grazie
