### ISSUE TITLE
Feed RSS con problema di encoding

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#22]
### Comportamento atteso e comportamento effettivo
Aprendo il [feed RSS](https://www.comune.palermo.it/feed/rss_opendata.xml) ci sono dei problemi di encoding

![image](https://user-images.githubusercontent.com/30607/43090237-1f7bc23c-8ea7-11e8-8ecb-9b183d33d7c2.png)

### Passi per riprodurre il problema

Aprire il feed in vista codice

```xml
<item>
<guid>https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1037</guid>
<title>Popolazione residente al 31/12/2017 per sezione di censimento, classi di etÃ  e sesso femminile</title>
<description>Elaborazione statistica dell&amp;#39;ufficio statistica effettuata sull&amp;#39;archivio dell&amp;#39;anagrafe comunale. situazione al 31 dicembre 2017
</description>
<link>https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1037</link>
<author>webmaster@comune.palermo.it (Comune di Palermo)</author>
<category>Dati sul territorio</category>
<pubDate>Mon, 23 Jul 2018 13:04:48 GMT</pubDate>
</item>
```

### Browser e sistema operativo usato

Chrome  68.0.3440.68 e Windows 10

**Comment by ComunePalermo** [comment]
bug risolto.

**Comment by aborruso** [comment]
Segnalo che una volta modificato il feed RSS, il problema si è attivato nel sito: vedi #23
