### ISSUE TITLE
Problema di encoding nelle pagine dei dataset

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#23]
### Comportamento atteso e comportamento effettivo

I caratteri accentati non sono renderizzati correttamente. Qui un esempio [https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1037](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1037)

![image](https://user-images.githubusercontent.com/30607/43308035-6ce4b548-9180-11e8-92e7-0c585e60470f.png)

### Passi per riprodurre il problema

Aprire la pagina di esempio e visualizzarla in un browser.

Nota: credo sia un problema connesso  in qualche modo a #12   e #22 

### Browser e sistema operativo usato

Chrome 68.0.3440.68 e Windows 10

**Comment by ComunePalermo** [comment]
Risolto
