### ISSUE TITLE
Dataset PERIMETRAZIONI CIRCOSCRIZIONI COMUNALI

### ISSUE THREAD

**Issue by pigreco** [ComuneDiPalermo/PortaleOpendata#27]
Salve, 

segnalo dei problemi che ho riscontrato paragonando il dataset PERIMETRAZIONI CIRCOSCRIZIONI COMUNALI [0] messo a disposizione dal portale [OPENDATA del Comune di Palermo](https://www.comune.palermo.it/opendata_menus.php) con lo stesso dataset messo a disposizione dall'ISTAT [1].

I problemi riscontrati sono:

1. la perimetrazione del Comune è differente da quella dell'ISTAT;

2. all'interno del file zippato del Comune manca il file [.prj](https://vsp.pnnl.gov/help/Vsample/ESRI_PRJ_File.htm) ovvero il file che contiene informazioni sul sistema di coordinate;

3. nell'ipotesi fosse corretta la perimetrazione distribuita dal Comune, segnalo che la feature della circoscrizione 1 (centro storico) il poligono non è correttamente tracciato in quanto presenta una linea fuori perimetro.

Allego uno screenshot di confronto, realizzato usando il software Open Source [QGIS](https://qgis.org/it/site/)

![image](https://user-images.githubusercontent.com/7631137/57519659-1c255d00-731c-11e9-9393-d25713da7690.png)

Per qualsiasi approfondimento, sono a disposizione.

Cordiali saluti

[0] https://www.comune.palermo.it/opendata_dld.php?id=265
[1] https://www.istat.it/it/archivio/104317

PS: questa issue segue una mail scritta in data 01/05/2019 

![image](https://user-images.githubusercontent.com/7631137/57520019-f6e51e80-731c-11e9-99cb-3e0aeecb15b5.png)

Grazie e buon lavoro!

**Comment by ComunePalermo** [comment]
Il dataset è stato corretto.

**Comment by pigreco** [comment]
Ho scaricato il dataset da qui: 
https://opendata.comune.palermo.it/opendata-dataset.php?dataset=265
perché nel link segnalato [qui](https://github.com/ComuneDiPalermo/PortaleOpendata/issues/27#issue-442644016) trovo ancora il vecchio shapefile.

Analizzando il nuovo shapefile pubblicato, noto (in ordine di priorità):
1. un errato posizionamento che lo rende **inutilizzabile**:

![image](https://user-images.githubusercontent.com/7631137/60273559-ae96b580-98f6-11e9-8e91-f3d79face916.png)

2. errori topologici (elementi sovrapposti circoscrizione 1 e 7):

![image](https://user-images.githubusercontent.com/7631137/60273990-8c516780-98f7-11e9-9fb6-e35935b2c3f6.png)

3. Tabella attributi non completa:

![image](https://user-images.githubusercontent.com/7631137/60274118-cc184f00-98f7-11e9-8cc4-2bbddf24ab3a.png)

Grazie e buon lavoro
