### ISSUE TITLE
proposta: inserire in home link alle linee guida citate

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#28]
Buongiorno,
in home si citano le linee guida: inserirei un link al documento.

Grazie

![image](https://user-images.githubusercontent.com/30607/57579469-78af8600-749c-11e9-8fbf-9d238a11b6dd.png)

**Comment by ComunePalermo** [comment]
Fatto

**Comment by aborruso** [comment]
Grazie
