### ISSUE TITLE
responsabile opendata

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#29]
Buongiorno,
nel nuovo sito non trovo una pagina in cui si fa riferimento a nome e modalità di contatto del responsabile(i) opendata del Comune. Sbaglio?

Se no, mi sembra che sia necessario inserire queste informazioni.

Grazie

**Comment by ComunePalermo** [comment]
Nelle pagine di dettaglio dei dataset è presente il link alla mail del responsabile opendata.
Nella pagina dei Credit è presente il responsabile opendata.

**Comment by aborruso** [comment]
Grazie
