### ISSUE TITLE
Il catalogo DCAT da errore 500

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#30]
Buongiorno,
l'URL https://opendata.comune.palermo.it/dcat/dcat.php restituisce "HTTP ERROR 500".

È utile che venga ripristinato anche perché è il punto di accesso del portale Europeo.

Saluti

**Comment by ComunePalermo** [comment]
Il dataset 1063 creava problemi, stiamo cercando di capire quali.
Intanto il servizio è stato ripristinato.
Grazie per la segnalazione

**Comment by aborruso** [comment]
Grazie a voi

**Comment by aborruso** [comment]
Buongiorno di nuovo errore 500 https://opendata.comune.palermo.it/dcat/dcat.php

**Comment by ComunePalermo** [comment]
Il dataset 1248 crea. E' stato disabilitato ed il servizio, che non ha problemi di funzionamento,  è stato ripristinato.
