### ISSUE TITLE
Come contattare il settore open data?

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#31]
Buongiorno,
nel footer c'è la PEC dell'ufficio protocollo. Mi pare troppo stringente, e che possa rallentare la possibilità di ricevere richieste/proposte.

Chiedo al responsabile opendata e al webmaster, di valutare l'opportunità di creare una pagina contatti. All'interno gli si potrebbe inserire:

- o un modulo per fare richieste;
- o un'email dedicata (opendata@comune.palermo.it), con inoltro al responsabile opendata;
- o il link qui, alla pagina delle issue;
- o anche tutte queste cose insieme.

Grazie

**Comment by ComunePalermo** [comment]
In calce ad ogni dataset è presente la mail del responsabile opendata per segnalare un commento.
Allo stato attuale non si prevedono ulteriori implementazioni.

**Comment by aborruso** [comment]
Buongiorno, io penso a casi d'uso diversi. 

Ad esempio, sono un utente, un'azienda, un ricercatore, ecc., che si sta occupando di dati aperti e vuole contattare l'ufficio opendata del comune. Apro il portale opendata e trovo sul footer soltanto una PEC generale. Non "passo" quindi da una pagina di un dataset.
Nella pagina credits (che comunque non è una pagina in cui vado per cercare modalità di contatto) c'è in ogni caso il nome del responsabile, ma non una sua email o il link alla pagina del suo profilo.

Potreste mettere nel footer l'email del responsabile, così come in calce ad ogni dataset.

Grazie
