### ISSUE TITLE
Inserire da qualche parte il riferimento a DCAT_AP-IT

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#5]
Il nuovo portale espone i metadati  secondo le [specifiche DCAT_AP-IT](https://www.dati.gov.it/content/dcat-ap-it-v10-profilo-italiano-dcat-ap-0), ma non se ne fa cenno in alcuna sezione del sito.

Penso che sia una cosa che da valore al sito e al lavoro che è stato fatto, ma sopratutto è un elemento fondamentale per gli sviluppatori, perché è l'accesso _machine to machine_.

Renderei l'endpoint pubblico, in una nuova pagina dedicata agli sviluppatori.

**Comment by ComunePalermo** [comment]
Inserito nel footer di pagina il link.
Grazie per la segnalazione
