### ISSUE TITLE
Il dataset sinistri stradali 2017

### ISSUE THREAD

**Issue by gbvitrano** [ComuneDiPalermo/PortaleOpendata#6]
### Comportamento atteso e comportamento effettivo
Il dataset sinistri stradali 2017 non viene caricato in anteprima e non è disponibile come risorsa

### Passi per riprodurre il problema
Aprire il link  [](https://opendata.comune.palermo.it/ws.php?id=1634&fmt=csv) https://opendata.comune.palermo.it/ws.php?id=1634&fmt=csv
### Browser e sistema operativo usato
Firefox, Chrome, Opera - Win 10

**Comment by aborruso** [comment]
@gbvitrano quale la pagina web del dataset? Io la inserirei

**Comment by gbvitrano** [comment]
Giusto... ecco il link :-)
[https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1014](https://opendata.comune.palermo.it/opendata-dataset.php?dataset=1014)

**Comment by gbvitrano** [comment]
adesso funziona, grazie.
Non si potrebbero mettere anche in formato zip?
