### ISSUE TITLE
Carattere errato nel titolo di un dataset

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#7]
### Comportamento atteso e comportamento effettivo
Il dataset https://opendata.comune.palermo.it/opendata-dataset.php?dataset=948 riporta nel titolo `QUALITÃ` e non `QUALITÀ`.

### Passi per riprodurre il problema
Aprire URL https://opendata.comune.palermo.it/opendata-dataset.php?dataset=948

### Browser e sistema operativo usato
Firefox 59, Win 10

**Comment by cirospat** [comment]
corretto in QUALITA'
https://opendata.comune.palermo.it/opendata-dataset.php?dataset=948
