### ISSUE TITLE
Il search sembra non fuzionare correttamente

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#8]
### Comportamento atteso e comportamento effettivo
Se cerco `CARTA TECNICA COMUNALE - UNITÀ VOLUMETRICHE` dovrei avere come risultato il dataset https://opendata.comune.palermo.it/opendata-dataset.php?dataset=269, invece ho zero risultati

### Passi per riprodurre il problema
- aprire https://opendata.comune.palermo.it/opendata-dataset.php?dataset=269
- inserire nel search `CARTA TECNICA COMUNALE - UNITÀ VOLUMETRICHE`

### Browser e sistema operativo usato
Chrome 66, Win 10

**Comment by ComunePalermo** [comment]
Bug risolto, si trattava di un problema di encoding nella composizione della stringa da inviare al motore google.
