### ISSUE TITLE
Tutte le pagine dei dataset hanno lo stesso <title> - Problemi SEO

### ISSUE THREAD

**Issue by aborruso** [ComuneDiPalermo/PortaleOpendata#9]
### Comportamento atteso e comportamento effettivo
Quando si fa una ricerca, ad esempio di `ELENCO IMMOBILI DI PROPRIETA' COMUNALE`, nella [pagina dei risultati](https://opendata.comune.palermo.it/search.php?q=+ELENCO+IMMOBILI+DI+PROPRIETA%27+COMUNALE&sa=Invia+richiesta) si ha una lista con titoli pressoché omologhi e che non riguardano il titolo del dataset.

![immagine](https://user-images.githubusercontent.com/30607/38380268-84d17266-3903-11e8-86c8-b17614be89ff.png)

Questo rende l'output della ricerca molto poco utilizzabile.

Questo dipende dal fatto che il `<title>` delle pagine non è dinamico e non è valorizzato con il titolo del dataset. 

Questo ha un grosso impatto generale, perché i motori di ricerca indicizzerano male e poco i dataset del portale.

Se si prova a fare una [ricerca su google](https://www.google.it/search?rlz=1C1GGRV_itIT742IT742&ei=2lbGWp2PEseaU4XpjbgH&q=site%3Ahttps%3A%2F%2Fopendata.comune.palermo.it+&oq=site%3Ahttps%3A%2F%2Fopendata.comune.palermo.it+&gs_l=psy-ab.3...14916.14916.0.15700.1.1.0.0.0.0.131.131.0j1.1.0....0...1c.1.64.psy-ab..0.0.0....0.gd77DZoomBk), si evididenzia che:

- i titoli mostrati rendono impossibile capire su quale hyperlink fare click;
- ci sono pochissimi risultati (100) rispetto al totale dei dataset (che sono circa 1000).

### Passi per riprodurre il problema
- Aprire la pagina di output di una ricerca https://opendata.comune.palermo.it/search.php?q=+ELENCO+IMMOBILI+DI+PROPRIETA%27+COMUNALE&sa=Invia+richiesta
- aprire un google site search http://bit.ly/2EmmVhn

### Browser e sistema operativo usato
Chrome 66, Win 10

**Comment by ComunePalermo** [comment]
Il link su cui puntava il motore di ricerca era quello del listato dei dataset ecco perché mancava nella title della pagina il nome del dataset.
Abbiamo escluso il listato dal motore di ricerca ed abbiamo incluso della title dellapagina di dettaglio il titolo del dataset.
Credo che si debba aspettare la nuova indicizzazione di google per verificare i risultato.

**Comment by aborruso** [comment]
@ComunePalermo io in questi casi non chiuderei la issue, sin quando la cosa non è verificata.

Solo come promemoria, al momento (è normale) è tutto come prima [https://www.google.it/search?rlz=1C1GGRV_itIT742IT742&biw=1366&bih=631&ei=qcxdW4vsNMGkafSJqrAN&q=site%3Ahttps%3A%2F%2Fopendata.comune.palermo.it+inurl%3Aopendata-dataset&oq=site%3Ahttps%3A%2F%2Fopendata.comune.palermo.it+inurl%3Aopendata-dataset&gs_l=psy-ab.3...18176.19864.0.20244.9.9.0.0.0.0.165.895.0j7.7.0....0...1.1.64.psy-ab..2.0.0....0.DtV5F-04xg4](https://www.google.it/search?rlz=1C1GGRV_itIT742IT742&biw=1366&bih=631&ei=qcxdW4vsNMGkafSJqrAN&q=site%3Ahttps%3A%2F%2Fopendata.comune.palermo.it+inurl%3Aopendata-dataset&oq=site%3Ahttps%3A%2F%2Fopendata.comune.palermo.it+inurl%3Aopendata-dataset&gs_l=psy-ab.3...18176.19864.0.20244.9.9.0.0.0.0.165.895.0j7.7.0....0...1.1.64.psy-ab..2.0.0....0.DtV5F-04xg4)
